apiVersion: apps/v1
kind: Deployment
metadata:
    name: feeds
    labels:
        app: feeds
spec:
  replicas: 1
  selector:
      matchLabels:
          app: feeds
  template:
      metadata:
          labels:
              app: feeds
      spec:
          containers:
          image: supermike2020/udagram-feeds
          - name: feeds
            ports:
            imagePullPolicy: Always          
            resources:
                requests:
                    memory: "64Mi"
                    cpu: "250m"
                limits:
                  memory: "1024Mi"
                  cpu: "500m"       
            - containerPort: 8080
            livenessProbe:
                httpGet:
                    path: /health
                    port: 8080
                initialDelaySeconds: 3
                periodSeconds: 3
